### ISSUE TITLE
user not authorized to perform upload_grade_with_comment calls

### ISSUE THREAD

**Issue by Yicheng-Lu-llll** [a2975667/canvas_grader#4]
I am following this [Link](https://community.canvaslms.com/t5/Admin-Guide/How-do-I-manage-API-access-tokens-as-an-admin/ta-p/89) to generate the API token but always get failed with thw canvas API calls upload_grade_with_comment.

The error message shows that I am not authorized to perform this action. I am wondering is this means I need a admain api token or something else I need to pay attention. I am assuming TA account!=admain.  Thanks a lot!

```
Traceback (most recent call last):
  File "C:\Users\lyc\Desktop\canvas_grader\main.py", line 50, in <module>
    grade_upload(submissions, filepath)
  File "C:\Users\lyc\Desktop\canvas_grader\src\grading.py", line 68, in grade_upload
    upload_grade_with_comment(
  File "C:\Users\lyc\Desktop\canvas_grader\src\canvas_wrapper.py", line 51, in upload_grade_with_comment
    submission.edit(comment={'text_comment': ta_comment},
  File "C:\Users\lyc\Desktop\canvas_grader\.venv\lib\site-packages\canvasapi\submission.py", line 74, in edit
    response = self._requester.request(
canvasapi.exceptions.Forbidden: {"status":"unauthorized","errors":[{"message":"user not authorized to perform that action"}]}
(.venv) PS C:\Users\lyc\Desktop\canvas_grader>`
```

**Comment by a2975667** [comment]
Thank you for reaching out! Can you check if the grading assignment is published or not? Canvas does not allow grade upload until you publish an assignment (you can select hide from student, but it must be published first).

**Comment by Yicheng-Lu-llll** [comment]
> Thank you for reaching out! Can you check if the grading assignment is published or not? Canvas does not allow grade upload until you publish an assignment (you can select hide from student, but it must be published first).

Thank you so much! It works now!

**Comment by a2975667** [comment]
#Todo catch error to provide more helpful reminder.
